// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJvUH3WoOvG3HFMJ6sPn4wLa6gzUZ1sGg',
    appId: '1:745268134134:web:8d6d72d31837a5265dacd7',
    messagingSenderId: '745268134134',
    projectId: 'maya-clone-app',
    authDomain: 'maya-clone-app.firebaseapp.com',
    storageBucket: 'maya-clone-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmNUU57thSAFGGhpPE7vN0bU9TtLnf964',
    appId: '1:745268134134:android:c9db4aeb11e7081b5dacd7',
    messagingSenderId: '745268134134',
    projectId: 'maya-clone-app',
    storageBucket: 'maya-clone-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHdsWctdYA4rwWnau-v9RRHEDGMSLA39s',
    appId: '1:745268134134:ios:70417e68c8cef6285dacd7',
    messagingSenderId: '745268134134',
    projectId: 'maya-clone-app',
    storageBucket: 'maya-clone-app.appspot.com',
    iosClientId:
        '745268134134-m9mfh6iogr9825kf2ghao1g55eo1im24.apps.googleusercontent.com',
    iosBundleId: 'com.example.mayaCloneApp',
  );
}
